# Generated by Django 5.1.3 on 2026-08-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Oddiy foydalanuvchi'), ('business', 'Biznes admin'), ('admin', 'Platforma admini')], db_index=True, default='user', max_length=10),
        ),
    ]
