# Generated by Django 5.1.3 on 2026-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_avatar_user_bio_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text='Bir marta berilgach qaytarilmaydi.', verbose_name='Bepul sinov ishlatilgan'),
        ),
    ]
