# Generated by Django 5.1.3 on 2026-08-22 10:24

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_has_used_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Google ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Raqam kiritilgan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Birinchi bron qilinganda so'raladi. Joy egasi shu raqamga qo'ng'iroq qiladi.", max_length=13, null=True, unique=True, validators=[account.validators.validate_phone_number], verbose_name='Aloqa raqami'),
        ),
    ]
