# Generated by Django 5.1.3 on 2026-08-22 14:02

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_google_sub_alter_user_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Bron yoki ariza berishda so'raladi. Takrorlanishi mumkin.", max_length=13, null=True, validators=[account.validators.validate_phone_number], verbose_name='Aloqa raqami'),
        ),
    ]
