# Generated by Django 5.1.3 on 2026-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_phone_number'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancelled_reservations_count',
            field=models.PositiveIntegerField(default=0, help_text="Faqat foydalanuvchining O'ZI bekor qilganlari. Joy egasi rad etgan bronlar bu yerga qo'shilmaydi.", verbose_name='Bekor qilgan bronlari'),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_bits',
            field=models.PositiveSmallIntegerField(db_index=True, default=100, help_text='1–100. Yangi hisob 100 Bit bilan boshlanadi.', verbose_name='Ishonchlilik (Bit)'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['trust_bits'], name='idx_user_trust_bits'),
        ),
    ]
