# Generated by Django 5.1.3 on 2026-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_telegram_username', models.CharField(default='uvente', help_text="@ belgisiz kiriting. Business ariza/to'lov oqimida foydalanuvchiga shu ko'rsatiladi.", max_length=32)),
            ],
            options={
                'verbose_name': 'Platforma sozlamalari',
                'verbose_name_plural': 'Platforma sozlamalari',
            },
        ),
    ]
