# Generated by Django 5.1.3 on 2026-08-19 17:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='room_deposit_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('99000'), help_text="Restoran Premium xonasi uchun oldindan to'lov.", max_digits=12),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='room_deposit_pro',
            field=models.DecimalField(decimal_places=2, default=Decimal('49000'), help_text="Restoran Pro xonasi uchun oldindan to'lov.", max_digits=12),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='subscription_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='venue_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('599000'), help_text="To'yxona zalini bron qilishda oldindan to'lov.", max_digits=12),
        ),
    ]
