# Generated by Django 5.1.3 on 2026-08-15 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restoran'), ('venue', "To'yxona")], max_length=15)),
                ('business_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending_payment', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Application',
                'verbose_name_plural': 'Business Applications',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restoran'), ('venue', "To'yxona")], max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='business_covers/')),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('rating_avg', models.FloatField(default=0)),
                ('telegram_username', models.CharField(max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='businesses.businessapplication')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('vip', 'VIP xona'), ('standard', 'Oddiy zal'), ('outdoor', 'Tashqi terrasa'), ('hall', "Katta zal (to'yxona)")], max_length=15)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_tier', models.CharField(blank=True, choices=[('premium', "Premium — 99 000 so'm"), ('pro', "Pro — 49 000 so'm")], help_text="Faqat restoranlar uchun. To'yxona xonalarida bo'sh qoldiring.", max_length=10, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['latitude', 'longitude'], name='businesses__latitud_6c4c1d_idx'),
        ),
    ]
