# Generated by Django 5.1.3 on 2026-08-15 10:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('vip', 'VIP xona'), ('standard', 'Oddiy zal'), ('outdoor', 'Tashqi terrasa')], max_length=15),
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('people', models.PositiveIntegerField(help_text='Zaldagi odamlar soni (masalan: 200, 500)')),
                ('all_price', models.DecimalField(decimal_places=2, help_text="Umumiy summa (masalan: 9 000 000 so'm)", max_digits=12)),
                ('deposit_price', models.DecimalField(decimal_places=2, default=Decimal('599000'), help_text="Bron qilishda oldindan to'lov (599 000 so'm)", max_digits=12)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
