# Generated by Django 5.1.3 on 2026-08-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_room_room_type_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price_per_slot',
        ),
    ]
