# Generated by Django 5.1.3 on 2026-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_remove_room_price_per_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='package',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
