# Generated by Django 5.1.3 on 2026-08-19 17:02

import common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_hall_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='business_photos/', validators=[common.validators.validate_image_file])),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Karuseldagi tartib.')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenuePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish_count', models.PositiveSmallIntegerField(choices=[(1, '1 xil taom'), (2, '2 xil taom'), (3, '3 xil taom')])),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ['dish_count'],
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-rating_avg', '-created_at'], 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='businessapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Application', 'verbose_name_plural': 'Business Applications'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-people', 'name']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['capacity', 'name']},
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='idx_biz_lat_lng',
            old_name='businesses__latitud_6c4c1d_idx',
        ),
        migrations.AddField(
            model_name='business',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Ish tugash vaqti (restoran).', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('milliy', 'Milliy taomlar'), ('yevropa', 'Yevropa oshxonasi'), ('fusion', 'Fusion'), ('sharqona', 'Sharqona'), ('fastfood', 'Fast food'), ('boshqa', 'Boshqa')], db_index=True, help_text='Faqat restoranlar uchun oshxona turi.', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='Tuman — qidiruvda nom bilan birga ishlatiladi (masalan: Yunusobod).', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='open_time',
            field=models.TimeField(blank=True, help_text='Ish boshlanish vaqti (restoran).', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, help_text="Denormalizatsiya: ro'yxat so'rovida COUNT(*) qilmaslik uchun."),
        ),
        migrations.AddField(
            model_name='hall',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='halls/', validators=[common.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='room',
            name='deposit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh qoldirilsa, tarifning platformadagi standart narxi olinadi.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', validators=[common.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restoran'), ('venue', "To'yxona")], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='business_covers/', validators=[common.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.FloatField(default=0, validators=[common.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.FloatField(default=0, validators=[common.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='rating_avg',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='telegram_username',
            field=models.CharField(blank=True, help_text="@ belgisiz. Mijoz depozit to'lovi uchun shu manzilga yozadi.", max_length=32),
        ),
        migrations.AlterField(
            model_name='hall',
            name='all_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Qat'iy umumiy summa (ixtiyoriy — odatda narx kishi boshiga hisoblanadi).", max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='deposit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Bron qilishda oldindan to'lov. Bo'sh qoldirilsa platforma standarti olinadi.", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='people',
            field=models.PositiveIntegerField(help_text='Zaldagi odamlar soni (masalan: 200, 500)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='deposit_tier',
            field=models.CharField(blank=True, choices=[('premium', 'Premium'), ('pro', 'Pro')], help_text="Faqat restoranlar uchun. To'yxona zallarida bo'sh qoldiring.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('vip', 'VIP xona'), ('standard', 'Oddiy zal'), ('outdoor', 'Tashqi terrasa')], db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_visible', 'business_type', '-rating_avg'], name='idx_biz_visible_type_rating'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_visible', 'district'], name='idx_biz_visible_district'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_visible', 'cuisine'], name='idx_biz_visible_cuisine'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='idx_biz_owner'),
        ),
        migrations.AddIndex(
            model_name='businessapplication',
            index=models.Index(fields=['status', '-created_at'], name='idx_app_status_created'),
        ),
        migrations.AddIndex(
            model_name='businessapplication',
            index=models.Index(fields=['applicant', 'status'], name='idx_app_applicant_status'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['business', 'people'], name='idx_hall_business_people'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['business', 'room_type'], name='idx_room_business_type'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['business', 'capacity'], name='idx_room_business_capacity'),
        ),
        migrations.AddField(
            model_name='businessphoto',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='venuepricing',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='businesses.business'),
        ),
        migrations.AddIndex(
            model_name='businessphoto',
            index=models.Index(fields=['business', 'order'], name='idx_bizphoto_business_order'),
        ),
        migrations.AddConstraint(
            model_name='venuepricing',
            constraint=models.UniqueConstraint(fields=('business', 'dish_count'), name='uniq_venue_pricing_business_dish'),
        ),
    ]
