# Generated by Django 5.1.3 on 2026-08-21 04:10

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businessphoto_venuepricing_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, help_text="+998XXXXXXXXX. Faqat ro'yxatdan o'tgan foydalanuvchilarga ko'rinadi.", max_length=13, validators=[account.validators.validate_phone_number], verbose_name='Aloqa raqami'),
        ),
        migrations.AlterField(
            model_name='business',
            name='telegram_username',
            field=models.CharField(blank=True, help_text="@ belgisiz. Mijoz depozit to'lovi uchun shu manzilga yozadi. Faqat ro'yxatdan o'tgan foydalanuvchilarga ko'rinadi.", max_length=32),
        ),
    ]
