# Generated by Django 5.1.3 on 2026-08-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_business_phone_number_and_more'),
        ('subscriptions', '0004_subscription_reminded_days_subscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapplication',
            name='plan',
            field=models.ForeignKey(blank=True, help_text="Bo'sh — bepul sinov arizasi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='subscriptions.subscriptionplan', verbose_name='Tanlangan tarif'),
        ),
    ]
