# Generated by Django 5.1.3 on 2026-08-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_businessapplication_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='all_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Butun zal uchun bir kunlik qat'iy summa (masalan 15 000 000). Qishloq to'yxonalarida narx odatda shunday: kishi boshiga emas, kunlik ijara. Bo'sh qoldirilsa mijozga narx ko'rsatilmaydi.", max_digits=14, null=True, verbose_name='Bir kunlik ijara narxi'),
        ),
    ]
