# Generated by Django 5.1.3 on 2026-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_hall_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='map_link',
            field=models.URLField(blank=True, help_text='Google Maps yoki Yandex Xaritadan "ulashish" havolasini shu yerga qo\'ying. Koordinatalar undan avtomatik olinadi.', max_length=500, verbose_name='Xaritadagi havola'),
        ),
    ]
