# Generated by Django 5.1.3 on 2026-09-06 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_business_map_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="1 — eng ko'p yulduz yig'gan joy. 0 — hali hisoblanmagan.", verbose_name="O'rin"),
        ),
        migrations.AddField(
            model_name='business',
            name='rating_points',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="Barcha sharhlardagi yulduzlar jami. O'rin shunga qarab beriladi.", verbose_name="Yulduzlar yig'indisi"),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type', '-rating_points'], name='idx_biz_type_points'),
        ),
    ]
