# Generated by Django 5.1.3 on 2026-08-15 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(db_index=True, default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.business')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.room')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'unique_together': {('room', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guests_count', models.PositiveIntegerField()),
                ('special_request', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Yakunlangan')], db_index=True, default='pending', max_length=15)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservations.availability')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.business')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('held', 'Ushlab turilgan'), ('refunded', 'Qaytarilgan (1 soat ichida bekor qilingan)'), ('forfeited', 'Qaytarilmaydi')], db_index=True, default='held', max_length=10)),
                ('refund_deadline', models.DateTimeField(help_text='Reservation yaratilgan payt + 1 soat. Shu vaqtgacha bekor qilinsa deposit qaytariladi.')),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deposit_refunds', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Deposit Transaction',
            },
        ),
    ]
