# Generated by Django 5.1.3 on 2026-08-15 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_hall_package'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.hall'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.hall'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.room'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'date', 'start_time'), name='uniq_room_slot'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('hall__isnull', False)), fields=('hall', 'date', 'start_time'), name='uniq_hall_slot'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hall__isnull', True), ('room__isnull', False)), models.Q(('hall__isnull', False), ('room__isnull', True)), _connector='OR'), name='availability_exactly_one_of_room_or_hall'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hall__isnull', True), ('room__isnull', False)), models.Q(('hall__isnull', False), ('room__isnull', True)), _connector='OR'), name='reservation_exactly_one_of_room_or_hall'),
        ),
    ]
