# Generated by Django 5.1.3 on 2026-08-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_hall_package'),
        ('reservations', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittransaction',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='deposittransaction',
            name='reservation',
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time'], 'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='availability',
            name='uniq_room_slot',
        ),
        migrations.RemoveConstraint(
            model_name='availability',
            name='uniq_hall_slot',
        ),
        migrations.RemoveConstraint(
            model_name='availability',
            name='availability_exactly_one_of_room_or_hall',
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_exactly_one_of_room_or_hall',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hall',
        ),
        migrations.AlterField(
            model_name='availability',
            name='room',
            field=models.ForeignKey(blank=True, help_text="Faqat restoran uchun. To'yxona uchun bo'sh qoldiriladi — to'yxonada bo'sh vaqt Room emas, butun business darajasida hisoblanadi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.room'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'date', 'start_time'), name='uniq_room_date_start_time'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', True)), fields=('business', 'date', 'start_time'), name='uniq_business_date_start_time_no_room'),
        ),
        migrations.DeleteModel(
            name='DepositTransaction',
        ),
    ]
