# Generated by Django 5.1.3 on 2026-08-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_hall_package'),
        ('reservations', '0003_remove_deposittransaction_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dish_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hall',
            field=models.ForeignKey(blank=True, help_text="Faqat to'yxona broni uchun — qaysi zal band qilingani.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.hall'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Faqat restoran broni uchun.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.room'),
        ),
    ]
