# Generated by Django 5.1.3 on 2026-08-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_deposit_amount_reservation_dish_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='availability',
            field=models.ForeignKey(blank=True, help_text="Bron tegishli bo'lgan kunlik bo'sh vaqt yozuvi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.availability'),
        ),
    ]
