# Generated by Django 5.1.3 on 2026-08-19 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businessphoto_venuepricing_alter_business_options_and_more'),
        ('reservations', '0005_alter_reservation_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='selected_menu',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['business', 'date', 'is_booked'], name='idx_avail_biz_date_booked'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['room', 'date'], name='idx_avail_room_date'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['date', 'is_booked'], name='idx_avail_date_booked'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['business', 'status', '-created_at'], name='idx_resv_biz_status_created'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', '-created_at'], name='idx_resv_user_created'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'availability', 'status'], name='idx_resv_room_avail_status'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hall', 'availability', 'status'], name='idx_resv_hall_avail_status'),
        ),
    ]
