# Generated by Django 5.1.3 on 2026-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_selected_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti'),
        ),
    ]
