# Generated by Django 5.1.3 on 2026-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='day_rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Bir kunlik ijara'),
        ),
    ]
