# Generated by Django 5.1.3 on 2026-08-19 17:02

import common.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businessphoto_venuepricing_alter_business_options_and_more'),
        ('reservations', '0006_reservation_selected_menu_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewphoto',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='image',
            field=models.ImageField(upload_to='review_photos/', validators=[common.validators.validate_image_file]),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['business', '-created_at'], name='idx_review_business_created'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='idx_review_user_created'),
        ),
        migrations.AddIndex(
            model_name='reviewphoto',
            index=models.Index(fields=['review'], name='idx_reviewphoto_review'),
        ),
    ]
