# Generated by Django 5.1.3 on 2026-08-19 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businessphoto_venuepricing_alter_business_options_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['subscription', '-created_at'], name='idx_payment_sub_created'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'trial_ends_at'], name='idx_sub_status_trial_end'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'subscription_ends_at'], name='idx_sub_status_sub_end'),
        ),
    ]
