# Generated by Django 5.1.3 on 2026-08-20 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businessphoto_venuepricing_alter_business_options_and_more'),
        ('subscriptions', '0003_plan_duration_and_price_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reminded_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Yuborilgan eslatmalar'),
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending_payment', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Egasining izohi')),
                ('admin_note', models.CharField(blank=True, max_length=255, verbose_name='Admin izohi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='businesses.business')),
                ('plan', models.ForeignKey(help_text='Egasi qaysi muddatni tanlagani.', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='subscriptions.subscriptionplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subscription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obuna arizasi',
                'verbose_name_plural': 'Obuna arizalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_subreq_status_created'), models.Index(fields=['business', '-created_at'], name='idx_subreq_biz_created')],
            },
        ),
    ]
