# Generated by Django 5.1.3 on 2026-08-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_hall_package'),
        ('catalog', '0002_remove_package_business_restaurantmenuitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuemenuitem',
            name='hall',
        ),
        migrations.AddField(
            model_name='venuemenuitem',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venue_menu_items', to='businesses.business'),
            preserve_default=False,
        ),
    ]
