# Generated by Django 5.1.3 on 2026-08-19 17:02

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businessphoto_venuepricing_alter_business_options_and_more'),
        ('catalog', '0003_remove_venuemenuitem_hall_venuemenuitem_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantmenuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Restaurant Menu Item'},
        ),
        migrations.AlterModelOptions(
            name='venuemenuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Venue Menu Item'},
        ),
        migrations.AddField(
            model_name='restaurantmenuitem',
            name='category',
            field=models.CharField(choices=[('starter', "Boshlang'ich"), ('soup', "Sho'rva"), ('main', 'Asosiy taom'), ('salad', 'Salat'), ('dessert', 'Desert'), ('drink', 'Ichimlik'), ('other', 'Boshqa')], db_index=True, default='main', max_length=15),
        ),
        migrations.AddField(
            model_name='venuemenuitem',
            name='category',
            field=models.CharField(choices=[('starter', "Boshlang'ich"), ('soup', "Sho'rva"), ('main', 'Asosiy taom'), ('salad', 'Salat'), ('dessert', 'Desert'), ('drink', 'Ichimlik'), ('other', 'Boshqa')], db_index=True, default='main', max_length=15),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_menu/', validators=[common.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='venuemenuitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='venue_menu/', validators=[common.validators.validate_image_file]),
        ),
        migrations.AddIndex(
            model_name='restaurantmenuitem',
            index=models.Index(fields=['business', 'is_available'], name='idx_rmenu_business_available'),
        ),
        migrations.AddIndex(
            model_name='restaurantmenuitem',
            index=models.Index(fields=['business', 'category'], name='idx_rmenu_business_category'),
        ),
        migrations.AddIndex(
            model_name='venuemenuitem',
            index=models.Index(fields=['business', 'category'], name='idx_vmenu_business_category'),
        ),
    ]
