# Generated by Django 5.1.3 on 2026-08-19 18:28

import common.validators
import content.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_uz', models.CharField(blank=True, max_length=300)),
                ('subtitle_ru', models.CharField(blank=True, max_length=300)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('cta_label_uz', models.CharField(blank=True, max_length=60, verbose_name='Tugma matni (uz)')),
                ('cta_label_ru', models.CharField(blank=True, max_length=60, verbose_name='Tugma matni (ru)')),
                ('cta_label_en', models.CharField(blank=True, max_length=60, verbose_name='Tugma matni (en)')),
                ('cta_url', models.CharField(blank=True, max_length=500, verbose_name='Tugma havolasi')),
                ('media_type', models.CharField(choices=[('none', 'Faqat matn'), ('image', 'Rasm'), ('video', 'Video')], default='none', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Tavsiya: 1600×700 px', null=True, upload_to='banners/', validators=[common.validators.validate_image_file])),
                ('video', models.FileField(blank=True, help_text='MP4 fayl. Yoki tashqi havolani `video_url` ga yozing.', null=True, upload_to='banners/video/')),
                ('video_url', models.URLField(blank=True, help_text='Tashqi video havolasi (mp4 yoki embed)')),
                ('placement', models.CharField(choices=[('hero', 'Bosh banner (asosiy)'), ('inline', 'Sahifa ichida'), ('sidebar', 'Yon panelda')], db_index=True, default='hero', max_length=10)),
                ('accent_color', models.CharField(blank=True, default='', help_text="Banner aksent rangi, masalan #C9A227. Bo'sh — standart oltin.", max_length=7)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, help_text="Bo'sh — darhol", null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text="Bo'sh — muddatsiz", null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active', 'order'], name='idx_banner_place_active')],
            },
            bases=(models.Model, content.models.TranslatedMixin),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('excerpt_uz', models.CharField(blank=True, max_length=300, verbose_name='Qisqacha (uz)')),
                ('excerpt_ru', models.CharField(blank=True, max_length=300, verbose_name='Qisqacha (ru)')),
                ('excerpt_en', models.CharField(blank=True, max_length=300, verbose_name='Qisqacha (en)')),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('news', 'Yangilik'), ('tip', 'Foydali maslahat'), ('event', 'Tadbir'), ('update', 'Platforma yangilanishi')], db_index=True, default='news', max_length=10)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/', validators=[common.validators.validate_image_file])),
                ('link_url', models.CharField(blank=True, help_text='Bosilganda ochiladigan sahifa (ixtiyoriy)', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Lentaning boshida turadi')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-is_pinned', 'order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', '-is_pinned', '-created_at'], name='idx_news_active_pinned')],
            },
            bases=(models.Model, content.models.TranslatedMixin),
        ),
    ]
