# Generated by Django 5.1.3 on 2026-08-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Bosh banner (asosiy)'), ('inline', 'Sahifa ichida'), ('sidebar', 'Yon panelda'), ('auth', 'Kirish sahifasi (chap tomon)')], db_index=True, default='hero', max_length=10),
        ),
    ]
