# Generated by Django 5.1.3 on 2026-08-20 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('reservation', 'Bron'), ('application', 'Ariza'), ('subscription', 'Obuna'), ('review', 'Sharh'), ('system', 'Tizim')], db_index=True, default='system', max_length=15)),
                ('level', models.CharField(choices=[('info', "Ma'lumot"), ('success', 'Muvaffaqiyat'), ('warning', 'Ogohlantirish')], default='info', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('link_url', models.CharField(blank=True, help_text='Bosilganda ochiladigan sahifa, masalan /bronlarim/', max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='idx_notif_user_read')],
            },
        ),
    ]
